interface Talent {
    id: string
    name: string
    title: string
    category: string
    skills: string[]
    hourlyRate: number
    rating: number
    reviews: number
    location: string
    verified: boolean
    level: string
    availability: string
    completedJobs: number
    bio: string
}
export interface TalentCardProps {
    talent: Talent
}
export const talentData: Talent[] = [
        {
            id: "1",
            name: "Alex Johnson",
            title: "Senior Blockchain Developer",
            category: "Development",
            skills: ["Solidity", "Ethereum", "Smart Contracts", "Web3.js", "DeFi"],
            hourlyRate: 85,
            rating: 4.9,
            reviews: 47,
            location: "Remote, USA",
            verified: true,
            level: "Expert",
            availability: "Full-time",
            completedJobs: 38,
            bio: "Blockchain developer with 5+ years of experience building DeFi protocols and smart contracts. Specialized in Ethereum ecosystem and security audits.",
        },
        {
            id: "2",
            name: "Sarah Chen",
            title: "UI/UX Designer for Web3",
            category: "Design",
            skills: ["UI/UX Design", "Figma", "Web3", "NFT", "Responsive Design"],
            hourlyRate: 65,
            rating: 4.8,
            reviews: 32,
            location: "Remote, Canada",
            verified: true,
            level: "Expert",
            availability: "Full-time",
            completedJobs: 27,
            bio: "Designer specializing in Web3 interfaces and NFT marketplaces. Creating intuitive and beautiful experiences for blockchain applications.",
        },
        {
            id: "3",
            name: "Michael Rodriguez",
            title: "Smart Contract Auditor",
            category: "Development",
            skills: ["Smart Contract Audits", "Solidity", "Security", "Ethereum", "Testing"],
            hourlyRate: 120,
            rating: 5.0,
            reviews: 19,
            location: "Remote, UK",
            verified: true,
            level: "Expert",
            availability: "Part-time",
            completedJobs: 24,
            bio: "Security-focused smart contract auditor with background in cybersecurity. Helped secure over $500M in contract value across DeFi protocols.",
        },
        {
            id: "4",
            name: "Emily Parker",
            title: "Blockchain Content Writer",
            category: "Writing",
            skills: ["Technical Writing", "Whitepapers", "Documentation", "Blockchain", "Research"],
            hourlyRate: 45,
            rating: 4.7,
            reviews: 28,
            location: "Remote, Australia",
            verified: false,
            level: "Intermediate",
            availability: "Full-time",
            completedJobs: 31,
            bio: "Technical writer specializing in blockchain documentation, whitepapers, and educational content. Making complex concepts accessible to all audiences.",
        },
        {
            id: "5",
            name: "David Kim",
            title: "Solana Developer",
            category: "Development",
            skills: ["Solana", "Rust", "React", "TypeScript", "Web3"],
            hourlyRate: 95,
            rating: 4.8,
            reviews: 15,
            location: "Remote, South Korea",
            verified: true,
            level: "Expert",
            availability: "Full-time",
            completedJobs: 12,
            bio: "Full-stack developer focused on Solana ecosystem. Built multiple dApps and NFT marketplaces with high performance and scalability.",
        },
        {
            id: "6",
            name: "Olivia Wilson",
            title: "Tokenomics Consultant",
            category: "Writing",
            skills: ["Tokenomics", "Economics", "Research", "Whitepaper", "DeFi"],
            hourlyRate: 110,
            rating: 4.9,
            reviews: 21,
            location: "Remote, Germany",
            verified: true,
            level: "Expert",
            availability: "Part-time",
            completedJobs: 18,
            bio: "Economics PhD specializing in token economic models and incentive design. Helping projects create sustainable and effective tokenomics.",
        },
        {
            id: "7",
            name: "James Thompson",
            title: "Frontend DApp Developer",
            category: "Development",
            skills: ["React", "TypeScript", "Web3.js", "ethers.js", "UI/UX"],
            hourlyRate: 75,
            rating: 4.6,
            reviews: 34,
            location: "Remote, France",
            verified: false,
            level: "Intermediate",
            availability: "Full-time",
            completedJobs: 29,
            bio: "Frontend developer specialized in building intuitive and responsive interfaces for decentralized applications across multiple blockchains.",
        },
        {
            id: "8",
            name: "Sophia Martinez",
            title: "NFT Artist & Designer",
            category: "Design",
            skills: ["NFT Design", "Digital Art", "Illustration", "3D Modeling", "Animation"],
            hourlyRate: 60,
            rating: 4.7,
            reviews: 42,
            location: "Remote, Spain",
            verified: true,
            level: "Expert",
            availability: "Part-time",
            completedJobs: 45,
            bio: "Digital artist creating unique NFT collections and metaverse assets. Combining traditional art techniques with blockchain technology.",
        },
        {
            id: "9",
            name: "Robert Lee",
            title: "Blockchain Marketing Specialist",
            category: "Marketing",
            skills: ["Growth Marketing", "Community Building", "Social Media", "Content Strategy", "Crypto"],
            hourlyRate: 55,
            rating: 4.5,
            reviews: 23,
            location: "Remote, Singapore",
            verified: false,
            level: "Intermediate",
            availability: "Full-time",
            completedJobs: 19,
            bio: "Marketing specialist with focus on blockchain projects. Expertise in community building, growth hacking, and go-to-market strategies for Web3.",
        },
    ]
